### ISSUE TITLE
作成画面デザイン

### ISSUE THREAD

**Issue by yui-szk** [jigintern/online-2024-e#6]
https://www.figma.com/design/Kth3mbQI0VkELPxFMmIAMR/cocktail?t=ThWFQr9uje8Hjl3u-1

**Comment by yui-szk** [comment]
メッセージ作成画面のデザインを作成しました
figma: https://www.figma.com/design/Kth3mbQI0VkELPxFMmIAMR/cocktail?t=ThWFQr9uje8Hjl3u-1

![Image](https://github.com/user-attachments/assets/23fe5c33-3620-421d-a2b1-204cb8b9116e)

**Comment by yui-szk** [comment]
@andnotand @5ouma @Ryo-7 

メッセージ作成画面のデザインを作成しました
figma: https://www.figma.com/design/Kth3mbQI0VkELPxFMmIAMR/cocktail?t=ThWFQr9uje8Hjl3u-1

![Image](https://github.com/user-attachments/assets/23fe5c33-3620-421d-a2b1-204cb8b9116e)

**Comment by Ryo-7** [comment]
ボタンの確認のボタンと、送信ボタンの色揃えたいかも

**Comment by yui-szk** [comment]
> ボタンの確認のボタンと、送信ボタンの色揃えたいかも

@andnotand @5ouma @Ryo-7 
確認ボタンの色を変更しました

![Image](https://github.com/user-attachments/assets/ec71df23-6859-4b44-b8fd-549b4d48f141)

**Comment by yui-szk** [comment]
レイヤーを綺麗にしました

**Comment by Ryo-7** [comment]
一旦これで実装して良さそうです 👍 

実装後、スマホとかで確認して、気になったところは直す感じにしましょう

LGTM！
